package ch.klara.luz.store.model;


/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductPricing implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String productCode;
	private int volume;
	private String pricePlan;
	private java.math.BigDecimal price;
	private int klaraPoints;
	private String testingDuration;
	private java.util.Date requestDate;
	private java.math.BigDecimal vatRate;
	private boolean vatIncluded;
	private String discount;
	private String promotionCode;
	private String productVariantCode;
	private Boolean hasUsedActivationCode;

	private String postageType;

	private String shippingRegion;

	private String envelopeSize;

	private Integer envelopeWeight;

	private Boolean coverPrint;

	private String featurePricePlan;

	@org.kie.api.definition.type.Label("override Billing Tenant")
	private String overrideTenantId;

	private String vatCode;

	public ProductPricing() {
	}

	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	public int getVolume() {
		return this.volume;
	}

	public void setVolume(int volume) {
		this.volume = volume;
	}

	public String getPricePlan() {
		return this.pricePlan;
	}

	public void setPricePlan(String pricePlan) {
		this.pricePlan = pricePlan;
	}

	public java.math.BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(java.math.BigDecimal price) {
		this.price = price;
	}

	public int getKlaraPoints() {
		return this.klaraPoints;
	}

	public void setKlaraPoints(int klaraPoints) {
		this.klaraPoints = klaraPoints;
	}

	public String getTestingDuration() {
		return this.testingDuration;
	}

	public void setTestingDuration(String testingDuration) {
		this.testingDuration = testingDuration;
	}

	public java.util.Date getRequestDate() {
		return this.requestDate;
	}

	public void setRequestDate(java.util.Date requestDate) {
		this.requestDate = requestDate;
	}

	public java.math.BigDecimal getVatRate() {
		return this.vatRate;
	}

	public void setVatRate(java.math.BigDecimal vatRate) {
		this.vatRate = vatRate;
	}

	public boolean isVatIncluded() {
		return this.vatIncluded;
	}

	public void setVatIncluded(boolean vatIncluded) {
		this.vatIncluded = vatIncluded;
	}

	public String getDiscount() {
		return this.discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

	public String getPromotionCode() {
		return this.promotionCode;
	}

	public void setPromotionCode(String promotionCode) {
		this.promotionCode = promotionCode;
	}

	public String getProductVariantCode() {
		return this.productVariantCode;
	}

	public void setProductVariantCode(String productVariantCode) {
		this.productVariantCode = productVariantCode;
	}

	public Boolean getHasUsedActivationCode() {
		return this.hasUsedActivationCode;
	}

	public void setHasUsedActivationCode(Boolean hasUsedActivationCode) {
		this.hasUsedActivationCode = hasUsedActivationCode;
	}

	public String getPostageType() {
		return this.postageType;
	}

	public void setPostageType(String postageType) {
		this.postageType = postageType;
	}

	public String getShippingRegion() {
		return this.shippingRegion;
	}

	public void setShippingRegion(String shippingRegion) {
		this.shippingRegion = shippingRegion;
	}

	public String getEnvelopeSize() {
		return this.envelopeSize;
	}

	public void setEnvelopeSize(String envelopeSize) {
		this.envelopeSize = envelopeSize;
	}

	public Integer getEnvelopeWeight() {
		return this.envelopeWeight;
	}

	public void setEnvelopeWeight(Integer envelopeWeight) {
		this.envelopeWeight = envelopeWeight;
	}

	public Boolean getCoverPrint() {
		return this.coverPrint;
	}

	public void setCoverPrint(Boolean coverPrint) {
		this.coverPrint = coverPrint;
	}

	public String getFeaturePricePlan() {
		return this.featurePricePlan;
	}

	public void setFeaturePricePlan(String featurePricePlan) {
		this.featurePricePlan = featurePricePlan;
	}

	public String getOverrideTenantId() {
		return this.overrideTenantId;
	}

	public void setOverrideTenantId(String overrideTenantId) {
		this.overrideTenantId = overrideTenantId;
	}

	public String getVatCode() {
		return this.vatCode;
	}

	public void setVatCode(String vatCode) {
		this.vatCode = vatCode;
	}

	public ProductPricing(String productCode, int volume,
                          String pricePlan, java.math.BigDecimal price,
                          int klaraPoints, String testingDuration,
                          java.util.Date requestDate, java.math.BigDecimal vatRate,
                          boolean vatIncluded, String discount,
                          String promotionCode,
                          String productVariantCode,
                          Boolean hasUsedActivationCode,
                          String postageType, String shippingRegion,
                          String envelopeSize, Integer envelopeWeight,
                          Boolean coverPrint, String featurePricePlan,
                          String overrideTenantId, String vatCode) {
		this.productCode = productCode;
		this.volume = volume;
		this.pricePlan = pricePlan;
		this.price = price;
		this.klaraPoints = klaraPoints;
		this.testingDuration = testingDuration;
		this.requestDate = requestDate;
		this.vatRate = vatRate;
		this.vatIncluded = vatIncluded;
		this.discount = discount;
		this.promotionCode = promotionCode;
		this.productVariantCode = productVariantCode;
		this.hasUsedActivationCode = hasUsedActivationCode;
		this.postageType = postageType;
		this.shippingRegion = shippingRegion;
		this.envelopeSize = envelopeSize;
		this.envelopeWeight = envelopeWeight;
		this.coverPrint = coverPrint;
		this.featurePricePlan = featurePricePlan;
		this.overrideTenantId = overrideTenantId;
		this.vatCode = vatCode;
	}

}